import createClient from "openapi-fetch";
import type { paths } from "./api"; // generated by openapi-typescript


export const createHanaClient = (params:{baseUrl:string}) => {
    return createClient<paths>({ baseUrl: params.baseUrl });
}


