import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query";
import type { paths } from "./types/v1"; // generated by openapi-typescript
import { clientEnv } from "../../../client-env";

const fetchClient = createFetchClient<paths>({
  baseUrl: clientEnv.NEXT_PUBLIC_SERVER_BASE_URL,
});

export const serverApi = createClient(fetchClient);
