import { prisma } from "../src/deps/prisma";

const seed = async () => {
  // TODO: seed languages
  await prisma.$connect();
  await prisma.language.createMany({
    data: [
      { ISOCode: "af", name: "Afrikaans", id: "af" },
      { ISOCode: "sq", name: "Albanian", id: "sq" },
      { ISOCode: "am", name: "Amharic", id: "am" },
      { ISOCode: "ar", name: "Arabic", id: "ar" },
      { ISOCode: "hy", name: "Armenian", id: "hy" },
      { ISOCode: "az", name: "Azerbaijani", id: "az" },
      { ISOCode: "eu", name: "Basque", id: "eu" },
      { ISOCode: "be", name: "Belarusian", id: "be" },
      { ISOCode: "bn", name: "Bengali", id: "bn" },
      { ISOCode: "bs", name: "Bosnian", id: "bs" },
      { ISOCode: "bg", name: "Bulgarian", id: "bg" },
      { ISOCode: "ca", name: "Catalan", id: "ca" },
      { ISOCode: "ceb", name: "Cebuano", id: "ceb" },
      { ISOCode: "zh", name: "Chinese (Simplified)", id: "zh" },
      { ISOCode: "zh-TW", name: "Chinese (Traditional)", id: "zh-TW" },
      { ISOCode: "co", name: "Corsican", id: "co" },
      { ISOCode: "hr", name: "Croatian", id: "hr" },
      { ISOCode: "cs", name: "Czech", id: "cs" },
      { ISOCode: "da", name: "Danish", id: "da" },
      { ISOCode: "nl", name: "Dutch", id: "nl" },
      { ISOCode: "en", name: "English", id: "en" },
      { ISOCode: "eo", name: "Esperanto", id: "eo" },
      { ISOCode: "et", name: "Estonian", id: "et" },
      { ISOCode: "fi", name: "Finnish", id: "fi" },
      { ISOCode: "fr", name: "French", id: "fr" },
      { ISOCode: "fy", name: "Frisian", id: "fy" },
      { ISOCode: "gl", name: "Galician", id: "gl" },
      { ISOCode: "ka", name: "Georgian", id: "ka" },
      { ISOCode: "de", name: "German", id: "de" },
      { ISOCode: "el", name: "Greek", id: "el" },
      { ISOCode: "gu", name: "Gujarati", id: "gu" },
      { ISOCode: "ht", name: "Haitian Creole", id: "ht" },
      { ISOCode: "ha", name: "Hausa", id: "ha" },
      { ISOCode: "haw", name: "Hawaiian", id: "haw" },
      { ISOCode: "he", name: "Hebrew", id: "he" },
      { ISOCode: "hi", name: "Hindi", id: "hi" },
      { ISOCode: "hmn", name: "Hmong", id: "hmn" },
      { ISOCode: "hu", name: "Hungarian", id: "hu" },
      { ISOCode: "is", name: "Icelandic", id: "is" },
      { ISOCode: "ig", name: "Igbo", id: "ig" },
      { ISOCode: "id", name: "Indonesian", id: "id" },
      { ISOCode: "ga", name: "Irish", id: "ga" },
      { ISOCode: "it", name: "Italian", id: "it" },
      { ISOCode: "ja", name: "Japanese", id: "ja" },
      { ISOCode: "jv", name: "Javanese", id: "jv" },
      { ISOCode: "kn", name: "Kannada", id: "kn" },
      { ISOCode: "kk", name: "Kazakh", id: "kk" },
      { ISOCode: "km", name: "Khmer", id: "km" },
      { ISOCode: "rw", name: "Kinyarwanda", id: "rw" },
      { ISOCode: "ko", name: "Korean", id: "ko" },
      { ISOCode: "ku", name: "Kurdish", id: "ku" },
      { ISOCode: "ky", name: "Kyrgyz", id: "ky" },
      { ISOCode: "lo", name: "Lao", id: "lo" },
      { ISOCode: "la", name: "Latin", id: "la" },
      { ISOCode: "lv", name: "Latvian", id: "lv" },
      { ISOCode: "lt", name: "Lithuanian", id: "lt" },
      { ISOCode: "lb", name: "Luxembourgish", id: "lb" },
      { ISOCode: "mk", name: "Macedonian", id: "mk" },
      { ISOCode: "mg", name: "Malagasy", id: "mg" },
      { ISOCode: "ms", name: "Malay", id: "ms" },
      { ISOCode: "ml", name: "Malayalam", id: "ml" },
      { ISOCode: "mt", name: "Maltese", id: "mt" },
      { ISOCode: "mi", name: "Maori", id: "mi" },
      { ISOCode: "mr", name: "Marathi", id: "mr" },
      { ISOCode: "mn", name: "Mongolian", id: "mn" },
      { ISOCode: "my", name: "Myanmar (Burmese)", id: "my" },
      { ISOCode: "ne", name: "Nepali", id: "ne" },
      { ISOCode: "no", name: "Norwegian", id: "no" },
      { ISOCode: "ny", name: "Nyanja (Chichewa)", id: "ny" },
      { ISOCode: "or", name: "Odia (Oriya)", id: "or" },
      { ISOCode: "ps", name: "Pashto", id: "ps" },
      { ISOCode: "fa", name: "Persian", id: "fa" },
      { ISOCode: "pl", name: "Polish", id: "pl" },
      { ISOCode: "pt", name: "Portuguese", id: "pt" },
      { ISOCode: "pa", name: "Punjabi", id: "pa" },
      { ISOCode: "ro", name: "Romanian", id: "ro" },
      { ISOCode: "ru", name: "Russian", id: "ru" },
      { ISOCode: "sm", name: "Samoan", id: "sm" },
      { ISOCode: "gd", name: "Scots Gaelic", id: "gd" },
      { ISOCode: "sr", name: "Serbian", id: "sr" },
      { ISOCode: "st", name: "Sesotho", id: "st" },
      { ISOCode: "sn", name: "Shona", id: "sn" },
      { ISOCode: "sd", name: "Sindhi", id: "sd" },
      { ISOCode: "si", name: "Sinhala (Sinhalese)", id: "si" },
      { ISOCode: "sk", name: "Slovak", id: "sk" },
      { ISOCode: "sl", name: "Slovenian", id: "sl" },
      { ISOCode: "so", name: "Somali", id: "so" },
      { ISOCode: "es", name: "Spanish", id: "es" },
      { ISOCode: "su", name: "Sundanese", id: "su" },
      { ISOCode: "sw", name: "Swahili", id: "sw" },
      { ISOCode: "sv", name: "Swedish", id: "sv" },
      { ISOCode: "tl", name: "Tagalog (Filipino)", id: "tl" },
      { ISOCode: "tg", name: "Tajik", id: "tg" },
      { ISOCode: "ta", name: "Tamil", id: "ta" },
      { ISOCode: "tt", name: "Tatar", id: "tt" },
      { ISOCode: "te", name: "Telugu", id: "te" },
      { ISOCode: "th", name: "Thai", id: "th" },
      { ISOCode: "tr", name: "Turkish", id: "tr" },
      { ISOCode: "tk", name: "Turkmen", id: "tk" },
      { ISOCode: "uk", name: "Ukrainian", id: "uk" },
      { ISOCode: "ur", name: "Urdu", id: "ur" },
      { ISOCode: "ug", name: "Uyghur", id: "ug" },
      { ISOCode: "uz", name: "Uzbek", id: "uz" },
      { ISOCode: "vi", name: "Vietnamese", id: "vi" },
      { ISOCode: "cy", name: "Welsh", id: "cy" },
      { ISOCode: "xh", name: "Xhosa", id: "xh" },
      { ISOCode: "yi", name: "Yiddish", id: "yi" },
      { ISOCode: "yo", name: "Yoruba", id: "yo" },
      { ISOCode: "zu", name: "Zulu", id: "zu" },
    ],
    skipDuplicates: true,
  });
  await prisma.$disconnect();
};

export default seed;
