/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/translations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Translate text */
        post: operations["postApiTranslations"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    postApiTranslations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    text: string;
                    sourceLanguage: string;
                    targetLanguage: string;
                };
                "multipart/form-data": {
                    text: string;
                    sourceLanguage: string;
                    targetLanguage: string;
                };
                "text/plain": {
                    text: string;
                    sourceLanguage: string;
                    targetLanguage: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        sourceText: string;
                        sourceLanguage: string;
                        targetLanguage: string;
                        translatedText: string;
                    };
                    "multipart/form-data": {
                        sourceText: string;
                        sourceLanguage: string;
                        targetLanguage: string;
                        translatedText: string;
                    };
                    "text/plain": {
                        sourceText: string;
                        sourceLanguage: string;
                        targetLanguage: string;
                        translatedText: string;
                    };
                };
            };
        };
    };
}
