import createClient from "openapi-fetch";
import type { paths } from "../lib/api/v1.d.ts"; // generated by openapi-typescript

export const translateTextWithGoogle = async (params: {
  sourceText: string;
  sourceLanguage: string;
  targetLanguage: string;
  context?: string;
}): Promise<string> => {
  if (params.sourceLanguage === params.targetLanguage) {
    return params.sourceText;
  }

  const res = await fetch(
    `https://translate.googleapis.com/translate_a/single?client=gtx&sl=${
      params.sourceLanguage
    }&tl=${params.targetLanguage}&dt=t&q=${encodeURIComponent(params.sourceText)}`
  );
  const data = await res.json();

  return data[0][0][0];
};

export const getGrindaTranslateFn = (params: { apiKey: string; baseUrl: string }) => {
  return async (translateParams: {
    sourceText: string;
    sourceLanguage: string;
    targetLanguage: string;
    context?: string;
  }): Promise<string> => {
    const client = createClient<paths>({ baseUrl: params.baseUrl });

    const { data, error } = await client.POST("/api/translations/ai-translate", {
      body: {
        sourceLanguage: translateParams.sourceLanguage,
        sourceText: translateParams.sourceText,
        targetLanguage: translateParams.targetLanguage,
        context: translateParams.context,
      },
      params: {
        header: {
          "api-key": params.apiKey,
        },
      },
    });

    if (error) {
      console.error({ error });
    }

    return data.translatedText;
  };
};
