import { envServer } from "@/env-server";
import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query";
import type { paths } from "./types/v1"; // generated by openapi-typescript

const fetchClient = createFetchClient<paths>({
	baseUrl: envServer.NEXT_PUBLIC_SERVER_BASE_URL,
	credentials: "include",
});

export const ellysiaClient = createClient(fetchClient);
