import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query";
import type { paths } from "./types/v1"; // generated by openapi-typescript

const fetchClient = createFetchClient<paths>({
	baseUrl: "http://localhost:8000",
});

export const ellysiaClient = createClient(fetchClient);
